#!/bin/bash
helm repo add datawire https://app.getambassador.io
helm repo add jetstack https://charts.jetstack.io
helm repo update

helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.12.0 --set installCRDs=true

kubectl apply -f https://app.getambassador.io/yaml/edge-stack/3.7.0/aes-crds.yaml
helm install -n ambassador --create-namespace edge-stack datawire/edge-stack
kubectl rollout status  -n ambassador deployment/edge-stack -w

kubectl apply -f 00-namespace.yml
kubectl apply -f 05-cluster-issuer.yml
kubectl apply -f 05-certs.yml
kubectl apply -f 10-services.yml
kubectl apply -f 20-configmap.yml
kubectl apply -f 40-deployment.yml
