apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: realnet
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
    persistence true
    persistence_location /mosquitto/data
    log_dest stdout
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: realnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:latest
          ports:
            - containerPort: 1883
              name: mqtt
          volumeMounts:
            - name: config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
            - name: data
              mountPath: /mosquitto/data
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: config
          configMap:
            name: mosquitto-config
        - name: data
          persistentVolumeClaim:
            claimName: realnet-data
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: realnet
spec:
  ports:
    - port: 1883
      targetPort: mqtt
      name: mqtt
  selector:
    app: mosquitto
