apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: realnet
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432        # Internal port for cluster communication
      targetPort: 5432  # Container port
    - name: external
      port: 5433        # External port for local access
      targetPort: 5432  # Maps to container port
  selector:
    app: postgresql
  externalTrafficPolicy: Local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: realnet
spec:
  selector:
    matchLabels:
      app: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgis/postgis:15-3.3
          env:
            - name: POSTGRES_DB
              value: realnet
            - name: POSTGRES_USER
              value: realnet
            - name: POSTGRES_PASSWORD
              value: realnet
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
          lifecycle:
            postStart:
              exec:
                command: 
                  - "sh"
                  - "-c"
                  - "sleep 10 && PGPASSWORD=realnet psql -U realnet -d realnet -c 'CREATE EXTENSION IF NOT EXISTS postgis;'"
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-data
