apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  namespace: realnet
data:
  POSTGRES_DB: realnet
  POSTGRES_USER: realnet
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: realnet
type: Opaque
data:
  POSTGRES_PASSWORD: cmVhbG5ldA== # base64 encoded 'realnet'
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: realnet
spec:
  serviceName: postgresql
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:latest
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgresql-config
            - secretRef:
                name: postgresql-secret
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "realnet"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "realnet"]
            initialDelaySeconds: 30
            periodSeconds: 20
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: realnet-postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: realnet
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgresql
