apiVersion: v1
kind: ServiceAccount
metadata:
  name: realnet
  namespace: realnet
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: realnet-cluster-role
rules:
  - apiGroups: [""]  # Core API group
    resources: ["pods", "services", "configmaps", "secrets", "namespaces", "persistentvolumes", "persistentvolumeclaims", "serviceaccounts"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: realnet-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: realnet
  namespace: realnet
roleRef:
  kind: ClusterRole
  name: realnet-cluster-role
  apiGroup: rbac.authorization.k8s.io
