apiVersion: v1
kind: ConfigMap
metadata:
  name: realnet-config
  namespace: realnet
data:
  REALNET_SERVER_HOST: "0.0.0.0"
  REALNET_SERVER_PORT: "8080"
  REALNET_DB_TYPE: "postgresql"
  REALNET_DB_HOST: "postgresql"
  REALNET_DB_PORT: "5432"
  REALNET_DB_NAME: "realnet"
  REALNET_DB_USER: "realnet"
  REALNET_MQTT_HOST: "mosquitto"
  REALNET_MQTT_PORT: "1883"
---
apiVersion: v1
kind: Secret
metadata:
  name: realnet-secret
  namespace: realnet
type: Opaque
data:
  REALNET_DB_PASS: cmVhbG5ldA== # base64 encoded 'realnet'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: realnet
  namespace: realnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realnet
  template:
    metadata:
      labels:
        app: realnet
    spec:
      containers:
        - name: realnet
          image: realnet:latest
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: realnet-config
            - secretRef:
                name: realnet-secret
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 60
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: realnet-data
---
apiVersion: v1
kind: Service
metadata:
  name: realnet
  namespace: realnet
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      name: http
  selector:
    app: realnet
