apiVersion: v1
kind: Service
metadata:
  name: wordpress-db
  namespace: realnet
  labels:
    app: wordpress-db
spec:
  ports:
    - port: 3306
      targetPort: mysql
      name: mysql
  selector:
    app: wordpress-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-db-pvc
  namespace: realnet
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-db
  namespace: realnet
  labels:
    app: wordpress-db
spec:
  selector:
    matchLabels:
      app: wordpress-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-db-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-db-secret
              key: password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-db-secret
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: wordpress-db-storage
          mountPath: /var/lib/mysql
        readinessProbe:
          exec:
            command:
            - bash
            - -c
            - mysql -u$MYSQL_USER -p$MYSQL_PASSWORD -e 'SELECT 1'
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - bash
            - -c
            - mysql -u$MYSQL_USER -p$MYSQL_PASSWORD -e 'SELECT 1'
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: wordpress-db-storage
        persistentVolumeClaim:
          claimName: wordpress-db-pvc
